version: 2

jobs:
  build-and-deploy:
    docker:
      - image: circleci/node:10.7
    steps:
      - checkout
      - restore_cache:
          key: node_modules-{{checksum "./package.json"}}-yarn
      - run:
          name: "Print out versions"
          command: |
            echo "node -v = $(node -v)"
            echo "npm -v = $(npm -v)"
            echo "yarn -v = $(yarn -v)"
      - run:
          name: "Install dependencies"
          command: yarn
      - save_cache:
          key: node_modules-{{checksum "./package.json"}}-yarn
          paths:
            - "./node_modules"
      - run:
          name: "Regenerate social media cards"
          command: make clean media
      - run:
          name: "Build site"
          command: yarn build
      - run:
          name: "Add commit reference and hashes to build output"
          command: |
            echo $(git rev-parse HEAD) > out/commit-hash
      - run:
          name: "Deploy site"
          command: |
            # ./node_modules/.bin/surge out/ rgausnet.surge.sh
            git clone git@github.com:1egoman/rgausnet.git
            cd rgausnet
            git sheckout gh-pages
            cp -R ../out/* .
            git add -A
            git commit -m "[ci skip] publish site update"
            git push origin gh-pages

workflows:
  version: 2
  commit:
    jobs:
      - build-and-deploy
  nightly:
    triggers:
      - schedule:
          cron: "0 0-23 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build-and-deploy
